ostadju/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from markdownx import urls as markdownx

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name="home"),
    url(r'^', include('people.urls', namespace='people')),
    url(r'^markdownx/', include(markdownx)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

people/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from people.views import signup, contact_us, profile, edit_profile, SearchProfiles, new_teacher_free_time, \
    delete_teacher_free_time, search_teachers_api_view, update_teacher_free_time, seen_notification, reserve_free_time, \
    undo_reserve_free_time, remove_user, forget_password, reset_password

app_name = "people"

urlpatterns = [
    url(r'^signup/$', signup, name="signup"),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='people/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^contact_us/$', contact_us, name="contact_us"),
    url(r'^profile/(?P<username>.*)/$', profile, name="profile"),
    url(r'^edit_profile/$', edit_profile, name="edit_profile"),
    url(r'^search_profiles/', SearchProfiles.as_view(), name="search_profiles"),
    url(r'^new_free_time$', new_teacher_free_time, name="new_free_time"),
    url(r'^delete_free_time/(?P<free_time_id>\d+)/$', delete_teacher_free_time, name="delete_free_time"),
    url(r'^search_teachers_api/$', search_teachers_api_view, name="search_teachers_api"),
    url(r'^update_teacher_free_time/(?P<free_time_id>.*)/$', update_teacher_free_time, name="update_teacher_free_time"),
    url(r'^seen_notification/(?P<notification_id>\d+)/$', seen_notification, name="seen_notification"),
    url(r'^reserve_free_time/(?P<free_time_id>\d+)/$', reserve_free_time, name="reserve_free_time"),
    url(r'^undo_reserve_free_time/(?P<free_time_id>\d+)/$', undo_reserve_free_time, name="undo_reserve_free_time"),
    url(r'^remove_user/$', remove_user, name="remove_user"),
    url(r'^forget_password/$', forget_password, name="forget_password"),
    url(r'^reset_password/(?P<username>.+)/(?P<activation_code>.+)/$', reset_password, name="reset_password"),
]

people/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.urls import reverse
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

from people.constants import GENDER_CHOICES


def get_picture_filename(instance, filename):
    return instance.username + "/" + filename


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    bio = MarkdownxField(max_length=500, blank=True, verbose_name="زندگی نامه", default="")
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="جنسیت", blank=True)
    picture = models.ImageField(null=True, upload_to=get_picture_filename, verbose_name="عکس پروفایل", blank=True)
    activation_code = models.UUIDField(null=False, default=uuid.uuid1)

    @property
    def get_bio(self):
        return markdownify(self.bio)

    def profile_url(self):
        return reverse("people:profile", kwargs={"username": self.username})

    def __str__(self):
        return self.username

    def json(self):
        return {
            'first_name': self.first_name,
            'last_name': self.last_name,
            'profile_url': self.profile_url(),
        }


class Student(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                primary_key=True,
                                related_name="student", )

    def __str__(self):
        return self.user.__str__()


class Teacher(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                primary_key=True,
                                related_name="teacher", )

    def __str__(self):
        return self.user.__str__()


class TeacherFreeTimes(models.Model):
    teacher = models.ForeignKey(Teacher, null=False, blank=False, verbose_name="استاد", on_delete=models.CASCADE)
    date = models.DateField(null=False, blank=False, verbose_name="تاریخ")
    start = models.TimeField(null=False, blank=False, verbose_name="ساعت شروع")
    end = models.TimeField(null=False, blank=False, verbose_name="ساعت پایان")
    student_capacity = models.PositiveIntegerField(null=False, blank=False, verbose_name="ظرفیت")
    reserved = models.ManyToManyField(Student, blank=True, default=[], through="ReservedFreeTimes")

    def free_capacity(self):
        return self.student_capacity - self.reserved.count()

    def __str__(self):
        return self.teacher.__str__() + " " + \
               self.date.__str__() + " " + \
               self.start.__str__() + " " + \
               self.end.__str__() + " " + \
               self.student_capacity.__str__()

    class Meta:
        verbose_name_plural = "Meetings"

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)
        if self.id is not None and self.free_capacity() < 0:
            raise ValidationError("ظرفیت جدید کمتر از تعداد رزروها است")
        if 'start' not in exclude:
            if 'end' not in exclude:
                self.clean_end()
                self.clean_start()

    def clean_end(self):
        if self.start >= self.end:
            raise ValidationError("زمان شروع باید قبل از زمان پایان فرصت باشد")

    def clean_start(self):
        have_intersect_error = "بازه زمانی انتخاب شده با فرصت های قبلی شما اشتراک دارد"
        q = TeacherFreeTimes.objects.filter(teacher=self.teacher, date=self.date)
        if self.id:
            q = q.filter(~Q(id=self.id))
        for x in q:
            if not ((x.end < self.start) or (self.end < x.start)):
                raise ValidationError(have_intersect_error)


class ReservedFreeTimes(models.Model):
    free_time = models.ForeignKey(TeacherFreeTimes, on_delete=models.CASCADE, null=False, blank=False)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=False, blank=False)

    class Meta:
        verbose_name_plural = 'Reserved Meetings'

    def __str__(self):
        return self.student.__str__() + " " + self.free_time.__str__()


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, related_name="notifications")
    text = models.TextField(null=False, blank=True)

    def __str__(self):
        return self.user.__str__() + " " + self.text

people/views.py
import uuid

from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView
from django.contrib.auth import logout
import socket
import netifaces
import re
from ostadju import settings
from people.decorators import is_teacher_check, is_student_check
from people.forms import SignUpForm, ContactUsForm, EditProfileUserForm, TeacherFreeTimeForm, ForgetPasswordForm, \
    ResetPasswordForm
from people.models import User, Teacher, TeacherFreeTimes, Notification, ReservedFreeTimes


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            print(form.__dict__)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'people/signup.html', {'form': form})


def contact_us(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(form.cleaned_data['title'],
                      "فرم تماس با ما با اطلاعات زیر پر شده است\n ایمیل:‌{} \n متن:{}".format(
                          form.cleaned_data['email'], form.cleaned_data['text']), from_email=form.cleaned_data['email'],
                      recipient_list=["ostadju@fastmail.com"],
                      fail_silently=True)
            return render(request, 'base.html', {'message': 'درخواست شما ثبت شد.'})

    else:
        form = ContactUsForm()
    return render(request, 'people/contact_us.html', {'form': form})

def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return render(request, 'base.html', {'message': 'کاربری با این نام کاربری وجود ندارد'})
    free_times = ""
    if user.is_teacher:
        free_times = TeacherFreeTimes.objects.filter(teacher=user.teacher)
    elif user.is_student:
        query_set = ReservedFreeTimes.objects.filter(student=request.user.student)
        free_times = []
        for query in query_set:
            free_times.append(query.free_time)
    return render(request, 'people/profile.html', {'user': user,
                                                   'free_times': free_times})


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileUserForm(instance=request.user, data=request.POST, files=request.FILES)

        if form.is_valid():
            form.save()
            return redirect(request.user.profile_url())
        else:
            message = 'اطلاعات وارد شده معتبر نمی‌باشد'
    else:
        message = ""
        form = EditProfileUserForm(instance=request.user)

    return render(request, 'people/edit_profile.html', {'form': form,
                                                        'message': message})


class SearchProfiles(ListView):
    model = Teacher
    template_name = "people/search_profiles.html"
    context_object_name = "teachers"

    def get_queryset(self):
        text = self.request.GET.get("search", "")
        query_set = Teacher.objects.filter(user__first_name__contains=text)
        query_set |= Teacher.objects.filter(user__last_name__contains=text)
        query_set |= Teacher.objects.filter(user__username__contains=text)
        return query_set


@login_required()
@user_passes_test(test_func=is_teacher_check)
def new_teacher_free_time(request):
    if request.method == "POST":
        instance = TeacherFreeTimes(teacher=request.user.teacher)
        form = TeacherFreeTimeForm(data=request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return render(request, 'base.html', {'message': "درخواست شما با موفقیت ثبت شد"})
    else:
        form = TeacherFreeTimeForm()
    return render(request, 'people/teacher_free_time_form.html', {"form": form})


def delete_teacher_free_time(request, free_time_id):
    try:
        teacher_free_time = TeacherFreeTimes.objects.get(id=free_time_id)
        if teacher_free_time.teacher != request.user.teacher:
            message = "فرصت مورد نظر متعلق به شما نیست"
        else:
            for student in teacher_free_time.reserved.all():
                teacher_user = teacher_free_time.teacher.user
                text = "فرصتی که شما از استاد " \
                       "{last_name} {first_name} " \
                       "در تاریخ {self.date} از ساعت {self.start} تا ساعت" \
                       " {self.end} گرفته بودید حذف گردید".format(self=teacher_free_time,
                                                                  first_name=teacher_user.first_name,
                                                                  last_name=teacher_user.last_name)
                notification = Notification(user=student.user, text=text)
                notification.save()
            teacher_free_time.delete()
            return redirect('home')
    except TeacherFreeTimes.DoesNotExist:
        message = 'فرصتی با شماره داده شده وجود ندارد'
    return render(request, 'base.html', {'message': message})


def search_teachers_api_view(request):
    query = request.GET.get('query', '')
    query_set = Teacher.objects.filter(user__first_name__contains=query)
    query_set |= Teacher.objects.filter(user__last_name__contains=query)
    query_set |= Teacher.objects.filter(user__username__contains=query)

    result = []
    for teacher in query_set:
        result.append(teacher.user.json())
    return JsonResponse(result, safe=False)


@login_required()
@user_passes_test(test_func=is_teacher_check)
def update_teacher_free_time(request, free_time_id):
    free_time = TeacherFreeTimes.objects.get(id=free_time_id)
    message = ""
    if free_time.teacher != request.user.teacher:
        message = "فرصت مورد نظر متعلق به شما نیست"
    if request.method == "POST":
        form = TeacherFreeTimeForm(data=request.POST, instance=free_time)
        if form.is_valid():
            form.save()
            return render(request, 'base.html', {'message': "درخواست شما با موفقیت ثبت شد"})
    else:
        form = TeacherFreeTimeForm(instance=free_time)
    return render(request, 'people/teacher_free_time_form.html', {"form": form, 'message': message})


@login_required()
def seen_notification(request, notification_id):
    try:
        notification = Notification.objects.get(id=notification_id)
        if notification.user != request.user:
            return render(request, 'home.html', {'message': 'اطلاعیه مورد نظر متعلق به شما نیست'})
        else:
            notification.delete()
            return redirect('home')
    except Notification.DoesNotExist:
        return render(request, 'home.html', {'message': 'اطلاعیه ای با شماره داده شده وجود ندارد'})


@login_required()
@user_passes_test(test_func=is_student_check)
def reserve_free_time(request, free_time_id):
    try:
        teacher_free_time = TeacherFreeTimes.objects.get(id=free_time_id)
    except TeacherFreeTimes.DoesNotExist:
        return render(request, 'home.html', {'message': 'فرصتی با شماره داده شده وجود ندارد'})
    if teacher_free_time.free_capacity() <= 0:
        return render(request, 'home.html', {'message': 'فرصت مورد نظر ظرفیت خالی ندارد'})
    x = ReservedFreeTimes(free_time=teacher_free_time,
                          student=request.user.student)
    x.save()
    return render(request, 'home.html', {'message': 'فرصت مورد نظر با موفقیت رزرو شد'})


@login_required()
@user_passes_test(test_func=is_student_check)
def undo_reserve_free_time(request, free_time_id):
    try:
        q = ReservedFreeTimes.objects.filter(free_time_id=free_time_id, student=request.user.student)
    except ReservedFreeTimes.DoesNotExist:
        message = 'فرصتی با شماره داده شده وجود ندارد یا شما آن فرصت را رزرو نکرده اید'
        return render(request, 'home.html', {'message': message})
    q.delete()
    return render(request, 'home.html', {'message': 'فرصت مورد نظر با موفقیت لغو رزرو شد'})


@login_required()
def remove_user(request):
    request.user.delete()
    logout(request)
    return render(request, 'home.html')

def forget_password(request):
    if request.method == "POST":
        form = ForgetPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)
                print("USER {}".format(user.__dict__))
                user.activation_code = uuid.uuid1()
                user.save()
                url_args = {'username': user.username, 'activation_code': str(user.activation_code)}
                ips = [netifaces.ifaddresses(iface)[netifaces.AF_INET][0]['addr'] for iface in netifaces.interfaces() if netifaces.AF_INET in netifaces.ifaddresses(iface)]
                ip = ""
                for i in ips:
                    if re.compile("192*").match(i):
                        ip = i
                        break
                if ip is None:
                    ip = "192.168.koft.koft not found [line 224 views.py forget_password]"
                url = "http://"+ip+":8000" + reverse('people:reset_password', kwargs=url_args)
                send_mail(user.username,
                          "جهت تنظیم مجدد گذرواژه روی لینک زیر کلیک کنید ." + "\n{url}".format(url=url),
                          from_email=settings.EMAIL_HOST_USER,
                          recipient_list=[email],
                          fail_silently=True)
                message = "ایمیل تغییر گذرواژه برای شما فرستاده شد"
            except User.DoesNotExist:
                message = 'کاربری با ایمیل داده شده وجود ندارد.'
            return render(request, 'home.html', {'message': message})

    else:
        form = ForgetPasswordForm()
    return render(request, 'people/forget_password.html', {'form': form})

people/templates/people/contact_us.html
{% extends "base.html" %}
{% block content %}
    <h2>ارتباط با ما</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button id="id_submit" type="submit">ارسال</button>
    </form>
{% endblock content %}

people/templates/people/edit_profile.html
{% extends "base.html" %}

{% block content %}
    <h2>پروفایل</h2>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" id="id_submit" value="ارسال"/></p>
    </form>
    {{ form.media }}

{% endblock content %}

people/templates/people/forget_password.html
{% extends "base.html" %}
{% block content %}
    <h2>فراموشی گذرواژه</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" id="id_submit">ارسال</button>
    </form>
{% endblock content %}

people/templates/people/login.html
{% extends "base.html" %}
{% block content %}
    <h2>ورود</h2>
    <form method="post">
        {% csrf_token %}
        {% if form.errors %}
            نام کاربری یا گذرواژه غلط است.
        {% endif %}
        <div>{{ form.username }} :نام کاربری</div>
        <div>{{ form.password }} :گذرواژه</div>
        <button type="submit" id="id_submit">ورود</button>
    </form>
    <a id="id_forget_password" href="{% url 'people:forget_password' %}">فراموشی گذرواژه</a>
{% endblock content %}

people/templates/people/new_teacher_free_time.html
{% extends "base.html" %}
{% block content %}

    <h2>ساخت فرصت جدید</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" id="form_submit">ارسال</button>
    </form>
    {{ form.media }}

{% endblock content %}

people/templates/people/profile.html
{% extends "base.html" %}

{% block content %}
    <h2>پروفایل</h2>

    {% if request.user == user %}
        <a href="{% url 'people:edit_profile' %}" id="id_edit_profile">تغییر تنظیمات</a>
        <!-- <a id="id_remove_user" href="{% url 'people:remove_user' %}">حذف کاربر و خروج از سامانه</a> !-->
        <a id="id_remove_user" onClick="confirm("آیا مطمئن هستید");" href="{% url 'people:remove_user' %}">حذف کاربر و خروج از سامانه</a>
        <p id="user-type">
            شما به عنوا
            <b id="type">
                {% if request.user.is_teacher %}
                    استاد
                {% else %}
                    دانشجو
                {% endif %}
            </b>
            وارد شده اید
        </p>
    {% endif %}
    <p>
        نام:
    </p>
    <p id="id_firstname">
        {{ user.first_name }}</p>
    <p>
        نام خانوادگی:
    </p>
    <p id="id_lastname">
        {{ user.last_name }}</p>
    <p>
        نام کاربری:
    </p>
    <p id="id_username">
        {{ user.username }}</p>
    <p id="id_gender">جنسیت :
        {{ user.get_gender_display }}</p>
    <p id="id_bio">زندگی نامه:
        <br>
        {{ user.get_bio|safe }}</p>
    {% if user.picture %}
        <img id="id_profile_image" src="{{ user.picture.url }}"/>
    {% endif %}
    {% if user.is_teacher %}
        <h2>فرصت ها</h2>
        <ul>
            {% for free_time in free_times %}
                <li id="id_meeting_{{ forloop.counter0 }}">
                    <div id="id_date">
                        {% if request.user.is_teacher and request.user.teacher == free_time.teacher %}
                            <a id="id_edit_meeting"
                               href="{% url 'people:update_teacher_free_time' free_time_id=free_time.id %}">
                                {{ free_time.date|safe }}</a>
                        {% else %}
                            <a id="id_reserve_meeting"
                               href="{% url 'people:reserve_free_time' free_time_id=free_time.id %}">{{ free_time.date|safe }}</a>
                        {% endif %}
                    </div>
                    <br>
                    <div id="id_start">
                        {{ free_time.start|safe }}
                    </div>
                    <br>
                    <div id="id_end">
                        {{ free_time.end|safe }}
                    </div>
                    <br>
                    <div id="id_student_capacity">
                        {{ free_time.student_capacity }}
                    </div>
                </li>
                <br>
            {% endfor %}
        </ul>
    {% elif request.user.is_student %}
        <h2>فرصت ها رزرو شده</h2>
        <ul>
            {% for free_time in free_times %}
                <li id="id_reserved_meeting_{{ forloop.counter0 }}">
                    <p>
                        <a id="id_cancel_meeting" href="{% url 'people:undo_reserve_free_time' free_time_id=free_time.id %}">
                            {{ free_time.teacher.user.get_full_name }}</a>
                    </p>
                    <p id="id_meeting_date">
                        {{ free_time.date|safe }}
                    </p>
                    <p id="id_meeting_start_time">
                        {{ free_time.start|safe }}
                    </p>

                    <p id="id_meeting_end_time">
                        {{ free_time.end|safe }}
                    </p>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock content %}

people/templates/people/remove_user.html
{% extends "base.html" %}
{% block content %}
    <h2>حذف کاربر</h2>
    <p>برای حذف کاربر نام کاربری خود را وارد کنید</p>
    <form method="post">
        {% csrf_token %}
        <label for="username">نام کاربری: </label>
        <input id="id_username" type="text" name="username" required="">
        <button id="id_submit" type="submit">حذف</button>
    </form>
{% endblock content %}

people/templates/people/reset_password.html
{% extends "base.html" %}
{% block content %}
    <h2>بازشانی گذرواژه</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" id="id_submit">ارسال</button>
    </form>
{% endblock content %}

people/templates/people/search_profiles.html
{% extends "base.html" %}
{% block content %}
    <ul>
        {% if teachers %}
            {% for teacher in teachers %}
                <li id="id_teacher_{{ forloop.counter0 }}">
                    <p>
                        نام کاربری :‌
                    </p>
                    <a href="{{ teacher.user.profile_url }}" id="id_username">
                        {{ teacher.user.username }}
                    </a>
                    <p>
                        نام :‌
                    </p>
                    <p id="id_firstname">
                        {{ teacher.user.first_name }}
                    </p>
                    <p>
                        نام خانوادگی :‌
                    </p>
                    <p id="id_lastname">
                        {{ teacher.user.last_name }}
                    </p>

                </li>
            {% endfor %}
        {% else %}
            <p>استادی یافت نشد</p>
        {% endif %}
    </ul>
{% endblock %}

people/templates/people/signup.html
{% extends "base.html" %}
{% block content %}
    <h2>ثبت نام</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.errors }}
        {% for element in form %}
            <p>
                {{ element.label }}:
                {{ element }}
            </p>

        {% endfor %}
        <button id="id_submit" type="submit">ثبت نام</button>
    </form>
{% endblock content %}

people/templates/people/teacher_free_time_form.html
{% extends "base.html" %}
{% block content %}

    <h2>ساخت فرصت جدید</h2>
    {% if form.instance.id %}
        <a id="id_remove_meeting" href="{% url 'people:delete_free_time' free_time_id=form.instance.id %}">حذف کردن فرصت</a>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" id="id_submit">ارسال</button>
    </form>
    {{ form.media }}

{% endblock content %}