ostadju/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from markdownx import urls as markdownx

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name="home"),
    url(r'^', include('people.urls', namespace='people')),
    url(r'^markdownx/', include(markdownx)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

people/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from people.views import signup, contact_us, profile, edit_profile, SearchProfiles, new_teacher_free_time, \
    delete_teacher_free_time, search_teachers_api_view, update_teacher_free_time, seen_notification, reserve_free_time, \
    undo_reserve_free_time, remove_user, forget_password, reset_password

app_name = "people"

urlpatterns = [
    url(r'^signup/$', signup, name="signup"),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='people/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^contact_us/$', contact_us, name="contact_us"),
    url(r'^profile/(?P<username>.*)/$', profile, name="profile"),
    url(r'^edit_profile/$', edit_profile, name="edit_profile"),
    url(r'^search_profiles/', SearchProfiles.as_view(), name="search_profiles"),
    url(r'^new_free_time$', new_teacher_free_time, name="new_free_time"),
    url(r'^delete_free_time/(?P<free_time_id>\d+)/$', delete_teacher_free_time, name="delete_free_time"),
    url(r'^search_teachers_api/$', search_teachers_api_view, name="search_teachers_api"),
    url(r'^update_teacher_free_time/(?P<free_time_id>.*)/$', update_teacher_free_time, name="update_teacher_free_time"),
    url(r'^seen_notification/(?P<notification_id>\d+)/$', seen_notification, name="seen_notification"),
    url(r'^reserve_free_time/(?P<free_time_id>\d+)/$', reserve_free_time, name="reserve_free_time"),
    url(r'^undo_reserve_free_time/(?P<free_time_id>\d+)/$', undo_reserve_free_time, name="undo_reserve_free_time"),
    url(r'^remove_user/$', remove_user, name="remove_user"),
    url(r'^forget_password/$', forget_password, name="forget_password"),
    url(r'^reset_password/(?P<username>.+)/(?P<activation_code>.+)/$', reset_password, name="reset_password"),
]

templates/base.html
{% load static %}
<html>
<title>استادجو</title>

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'markdownx/admin/css/markdownx.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'markdownx/js/markdownx.js' %}">
    <script type="text/javascript" src="{% static 'autocomplete.js' %}" async></script>
</head>
<body>
<nav id="id_navbar">
    <a id="id_navbar_home" href="{% url 'home' %}">خانه</a>
    {% if request.user.is_authenticated %}
        <a id="id_navbar_logout" href="{% url 'people:logout' %}">خروج</a>
        <a id="id_navbar_profile" href="{{ request.user.profile_url }}">پروفایل</a>
        {% if request.user.is_teacher %}
            <a id="id_navbar_meeting" href="{% url 'people:new_free_time' %}">اضافه کردن فرصت</a>
        {% endif %}
    {% else %}
        <a id="id_navbar_login" href="{% url 'people:login' %}">ورود</a>
        <a id="id_navbar_signup" href="{% url 'people:signup' %}">ثبت نام</a>
    {% endif %}
    <a id="id_navbar_contact_us" href="{% url 'people:contact_us' %}">تماس با ما</a>
</nav>
<br>
<div id="id_search_profiles">
    <form id="id_search_profiles_form" action="{% url 'people:search_profiles' %}" method="get">
        <input id="id_search_profiles_input" type="text" placeholder="جستجو..." name="search" required/>
        <button id="id_search_profiles_button" type="submit">برو</button>
    </form>
    <div id="autocomplete_results"></div>
</div>
{% if message %}
    <strong id="message">{{ message }}</strong>
    <br>
    <br>
{% endif %}
{% block content %}
{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
    <div id="welcome">به سامانه استادجو خوش آمدید.</div>
    {% if request.user.is_authenticated %}
        <ul id="notifications">
            {% for notification in request.user.notifications.all %}
                <li id="notification-{{ forloop.counter0 }}">
                    <a id="seen-notification-{{ forloop.counter0 }}"
                       href="{% url 'people:seen_notification' notification_id=notification.id %}">
                        {{ notification.text }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock %}